apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-faro
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: metrics
      username: metrics_user
      tlsSkipVerify: true
    secureJsonData:
      password: metrics_pass_123
    isDefault: true
    editable: true